logging:
  level:
    root: DEBUG
  file:
    name: logs/mxpusers.log
server:
  port: 8095

spring:
  datasource:
    url: jdbc:informix-sqli://192.168.1.2:9088/educa:INFORMIXSERVER=ol_database
    username: informix
    password: MP-PMI*
    driver-class-name: com.informix.jdbc.IfxDriver
  application:
    name: mediaxp-users
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.InformixDialect

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.3:8761/eureka/
  instance:
    appname: mediaxp-users
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    instance-id: